In [71]:
import numpy as np
from numpy import pi

In [72]:
a=np.array([[1,2,3],[12,99,0],[91,71234,123,19]])

C:\Users\Msc 1\AppData\Local\Temp\ipykernel_8500\3580234402.py:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  a=np.array([[1,2,3],[12,99,0],[91,71234,123,19]])


In [73]:
a.dtype

dtype('O')

In [74]:
print(a)


[list([1, 2, 3]) list([12, 99, 0]) list([91, 71234, 123, 19])]


In [75]:
b=np.array([1.2,2.3,2.0,9.1])

In [76]:
b.dtype

dtype('float64')

In [77]:
b

array([1.2, 2.3, 2. , 9.1])

In [78]:
c=complex(12,12)
d=complex(12,99)
e=c+d
e

(24+111j)

In [79]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [80]:
e=np.ones((2,3,4),dtype=np.int64)

In [81]:
e.dtype

dtype('int64')

In [82]:
print(e)

[[[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]

 [[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]]


In [83]:
np.linspace(0,2,9)

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ])

In [84]:
x=np.linspace(0,2*pi,100)

In [85]:
f=np.sin(x)

In [86]:
y=np.linspace(0,pi/2,4)
y

array([0.        , 0.52359878, 1.04719755, 1.57079633])

In [87]:
np.sin(y)

array([0.       , 0.5      , 0.8660254, 1.       ])

In [88]:
def trig(y):
    print(f"the sin values are {np.sin(y)}")

In [89]:
k=int(input("enter the angle for sin: "))
trig(k)

the sin values are 0.8939966636005579


In [90]:
b=np.arange(24).reshape(2,3,4)

In [91]:
b

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [92]:
print(np.arange(1000).reshape(5,10,20))

[[[  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16
    17  18  19]
  [ 20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35  36
    37  38  39]
  [ 40  41  42  43  44  45  46  47  48  49  50  51  52  53  54  55  56
    57  58  59]
  [ 60  61  62  63  64  65  66  67  68  69  70  71  72  73  74  75  76
    77  78  79]
  [ 80  81  82  83  84  85  86  87  88  89  90  91  92  93  94  95  96
    97  98  99]
  [100 101 102 103 104 105 106 107 108 109 110 111 112 113 114 115 116
   117 118 119]
  [120 121 122 123 124 125 126 127 128 129 130 131 132 133 134 135 136
   137 138 139]
  [140 141 142 143 144 145 146 147 148 149 150 151 152 153 154 155 156
   157 158 159]
  [160 161 162 163 164 165 166 167 168 169 170 171 172 173 174 175 176
   177 178 179]
  [180 181 182 183 184 185 186 187 188 189 190 191 192 193 194 195 196
   197 198 199]]

 [[200 201 202 203 204 205 206 207 208 209 210 211 212 213 214 215 216
   217 218 219]
  [220 221 222 223 224 225 226 227 228 22

import sys
np.set_printoptions(threshold=sys.maximize)

In [93]:
b=np.arange(12).reshape(3,4)
b


array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [94]:
b.sum(axis=1)

array([ 6, 22, 38])